[tool.pytest-watcher]
clear = true
ignore_patterns = [".\\env\\*"]

[tool.pytest.ini_options]
addopts = "-p no:faker -s"
testpaths = ["tests"]
markers = ["unit", "integration", "slow"]

[tool.black]
line-length = 80